### ISSUE TITLE
Open links embedded in comments automatically in a new tab

### ISSUE THREAD

**Issue by hannele** [opinsys/puavo-ticket#159]

**Comment by hannele** [comment]
No!

**Comment by epeli** [comment]
Internal links will be opened in the same window without a page reload.

Also the internal links will be abbreviated now from

    https://support.opinsys.fi/ticket/1/discuss

to

    /ticket/1/discuss

Also fixes the issue reported by @ptoivola of links without http://
prefix not opening.
